### ISSUE TITLE
BucketName is empty

### ISSUE THREAD

**Issue by AlixBa** [jamhall/s3rver#185]
```xml
<?xml version="1.0" encoding="UTF-8"?>
<ListBucketResult xmlns="http://doc.s3.amazonaws.com/2006-03-01">
  <IsTruncated>false</IsTruncated>
  <Marker/>
  <Name/>
  <Prefix/>
  <MaxKeys>1000</MaxKeys>
```

when using the bucketname from the ListBucketResult
```
java.lang.IllegalArgumentException: BucketName cannot be empty
	at com.amazonaws.util.ValidationUtils.assertStringNotEmpty(ValidationUtils.java:89)
	at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:1374)
	at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:1271)
```

regression? https://github.com/jamhall/s3rver/pull/100/files

**Comment by n1ru4l** [comment]
Seems so 😕

https://github.com/jamhall/s3rver/blob/d69913a8c68eec84fbec5080996ba63336fe6102/lib/controllers.js#L311-L324

**Comment by AlixBa** [comment]
Thanks @specialkk @n1ru4l :)
Reactive and efficient :D
