### ISSUE TITLE
Sending empty list of objects with s3.deleteObjects causes a crash. 

### ISSUE THREAD

**Issue by lalnuo** [jamhall/s3rver#223]
Hi! Following code will result an error: 

```javascript
s3.deleteObjects(
        {
          Bucket: config.BUCKET_NAME,
          Delete: {
            Objects: []
          }
        }
      );
```

Causes: 

```
Uncaught TypeError: Cannot read property 'map' of undefined
      at xml2js.parseString (node_modules/s3rver/lib/controllers.js:114:45)
      at Parser.<anonymous> (node_modules/xml2js/lib/xml2js.js:489:18)
      at Parser.emit (domain.js:421:20)
      at SAXParser.onclosetag (node_modules/xml2js/lib/xml2js.js:447:26)
      at emit (node_modules/sax/lib/sax.js:640:35)
      at emitNode (node_modules/sax/lib/sax.js:645:5)
      at closeTag (node_modules/sax/lib/sax.js:905:7)
      at SAXParser.write (node_modules/sax/lib/sax.js:1306:13)
      at Parser.exports.Parser.Parser.parseString (node_modules/xml2js/lib/xml2js.js:508:31)
      at Parser.parseString (node_modules/xml2js/lib/xml2js.js:7:59)
      at Object.exports.parseString (node_modules/xml2js/lib/xml2js.js:540:19)
      at deleteObjects (node_modules/s3rver/lib/controllers.js:113:12)
      at req.pipe.data (node_modules/s3rver/lib/controllers.js:517:13)
      at ConcatStream.<anonymous> (node_modules/concat-stream/index.js:36:43)
      at ConcatStream.emit (domain.js:421:20)
      at finishMaybe (node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:620:14)
      at afterWrite (node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:482:3)
      at process._tickCallback (internal/process/next_tick.js:114:19)
```

**Comment by c24w** [comment]
Whilst this has stopped the server from crashing, the real S3 actually rejects requests which contain an empty `Objects` array:

```
MalformedXML: The XML you provided was not well-formed or did not validate against our published schema
    at Request.extractError (/var/task/node_modules/aws-sdk/lib/services/s3.js:585:35)
```

So the behaviour gives a false-positive compared to the real thing.

**Comment by kherock** [comment]
@c24w we don't validate against those schemas directly (yet), but it shouldn't be difficult to handle this particular case. I think most of the maintainers, myself included, have been pretty busy lately, so a PR would be very welcome. I've opened #372 to track this.
