### ISSUE TITLE
`AWS authentication requires a valid Date or x-amz-date header`

### ISSUE THREAD

**Issue by feuGeneA** [jamhall/s3rver#447]
I'm trying to use the AWS CLI to connect to my s3rver instance, and I'm getting the error message in the title.

I'm starting my server like this:
```javascript
const fs = require('fs');
const S3rver = require('s3rver');

const port = 8081;

new S3rver({
  port: port,
  hostname: 'localhost',
  silent: false,
  cors: require.resolve("s3rver/example/cors.xml"),
  directory: '/home/gene/dev/0x-monorepo/contracts/asset-proxy/s3rver_root',
  removeBucketsOnClose: true,
  configureBuckets: [
      {
          name: "doc-jsons",
          configs: [fs.readFileSync(require.resolve("s3rver/example/cors.xml"))]
      }
  ]
}).run((err, host, port) => {
  if(err) {
    return Promise.reject(err);
  }
  Promise.resolve();
});
```

and I'm trying to use the AWS CLI like this:

```
$ AWS_ACCESS_KEY=S3RVER \
  AWS_SECRET_ACCESS_KEY=S3RVER \
  aws \
      --endpoint-url http://127.0.0.1:8081 \
      s3 ls
An error occurred (AccessDenied) when calling the ListBuckets operation: AWS authentication requires a valid Date or x-amz-date header
```

Does s3rver need to add support for a Date or x-amz-date header in order for this to work?  Or  perhaps there's some way I can tell the `aws` CLI to ignore this situation?  Or...?

**Comment by kherock** [comment]
I actually wasn't able to reproduce this with the example you gave me (though the `AWS_ACCESS_KEY` env variable should actually be named `AWS_ACCESS_KEY_ID`). Can you double check you're experiencing this on the latest 3.0.3 release?

P.S. `new S3rver.run()` returns a Promise if you omit the callback. Also it looks like you're using a mix of options from the old 2.x branch. The readme should be up-to-date regarding all the available options there.

**Comment by feuGeneA** [comment]
Thanks for the reply and the tips.

I confirmed that I am indeed experiencing this on the 3.0.3 release.

I've spruced up my source according to your suggestions (and I had already made some other changes), such that currently I have:

```TypeScript
import * as fs from 'fs';

import S3rver = require('s3rver');
import * as yargs from 'yargs';

const argv = yargs
    .option('directory', { type: 'string', description: 'path to folder which will contain root s3 data' })
    .demandOption('directory')
    .option('port', { type: 'number', description: 'port to listen for clients on' })
    .demandOption('port')
    .help().argv;

(async () => {
    await new S3rver({
        port: argv.port,
        address: 'localhost',
        silent: false,
        directory: argv.directory,
        configureBuckets: [
            { name: 'doc-jsons', configs: [fs.readFileSync(require.resolve('s3rver/example/cors.xml'))] },
        ],
    }).run();
})();
```

And I'm calling it with `node ./packages/monorepo-scripts/lib/host_local_s3.js --port 8081 --directory local_s3_root`.

I corrected the environment variable name to AWS_ACCESS_KEY_ID, but that didn't seem to change anything.

I also tried adding `--debug` to the `aws` command.  For one thing, that showed that I got the env vars right: `INFO - Found credentials in environment variables`.

But more importantly, `aws --debug` showed that this `Date or x-amz-date` message is coming from s3rver: `Response body:
b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>AccessDenied</Code><Message>AWS authentication requires a valid Date or x-amz-date header</Message></Error>'`

<details><summary>Full `aws --debug` output</summary>
<p>

```
$ AWS_ACCESS_KEY_ID=S3RVER   AWS_SECRET_ACCESS_KEY=S3RVER   aws       --endpoint-url http://127.0.0.1:8081       s3 ls --debug
2019-04-24 10:48:18,976 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/1.11.13 Python/3.5.3 Linux/4.9.0-8-amd64 botocore/1.4.70
2019-04-24 10:48:18,976 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['--endpoint-url', 'http://127.0.0.1:8081', 's3', 'ls', '--debug']
2019-04-24 10:48:18,976 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_scalar_parsers at 0x7f768fbc7f28>
2019-04-24 10:48:18,976 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_assume_role_provider_cache at 0x7f768ea46c80>
2019-04-24 10:48:18,977 - MainThread - botocore.credentials - DEBUG - Skipping environment variable credential check because profile name was explicitly set.
2019-04-24 10:48:18,977 - MainThread - botocore.hooks - DEBUG - Event building-command-table.s3: calling handler <function add_waiters at 0x7f768fbdb378>
2019-04-24 10:48:18,978 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.s3.anonymous: calling handler <function uri_param at 0x7f768ea777b8>
2019-04-24 10:48:18,978 - MainThread - botocore.hooks - DEBUG - Event building-command-table.ls: calling handler <function add_waiters at 0x7f768fbdb378>
2019-04-24 10:48:18,979 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.ls.page-size: calling handler <function uri_param at 0x7f768ea777b8>
2019-04-24 10:48:18,979 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.ls.request-payer: calling handler <function uri_param at 0x7f768ea777b8>
2019-04-24 10:48:18,979 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.ls.anonymous: calling handler <function uri_param at 0x7f768ea777b8>
2019-04-24 10:48:18,979 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.ls.summarize: calling handler <function uri_param at 0x7f768ea777b8>
2019-04-24 10:48:18,979 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.custom.ls: calling handler <awscli.argprocess.ParamShorthandParser object at 0x7f768ea1b828>
2019-04-24 10:48:18,979 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.ls.paths: calling handler <function uri_param at 0x7f768ea777b8>
2019-04-24 10:48:18,979 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.ls.human-readable: calling handler <function uri_param at 0x7f768ea777b8>
2019-04-24 10:48:18,979 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.custom.ls: calling handler <awscli.argprocess.ParamShorthandParser object at 0x7f768ea1b828>
2019-04-24 10:48:18,979 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: env
2019-04-24 10:48:18,979 - MainThread - botocore.credentials - INFO - Found credentials in environment variables.
2019-04-24 10:48:18,980 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/lib/python3/dist-packages/botocore/data/endpoints.json
2019-04-24 10:48:18,984 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/lib/python3/dist-packages/botocore/data/s3/2006-03-01/service-2.json
2019-04-24 10:48:18,992 - MainThread - botocore.client - DEBUG - Registering retry handlers for service: s3
2019-04-24 10:48:18,996 - MainThread - botocore.hooks - DEBUG - Event creating-client-class.s3: calling handler <function add_generate_presigned_post at 0x7f768f2d86a8>
2019-04-24 10:48:18,996 - MainThread - botocore.hooks - DEBUG - Event creating-client-class.s3: calling handler <function add_generate_presigned_url at 0x7f768f2d6c80>
2019-04-24 10:48:19,002 - MainThread - botocore.endpoint - DEBUG - Setting s3 timeout as (60, 60)
2019-04-24 10:48:19,003 - MainThread - botocore.client - DEBUG - Using S3 path style addressing.
2019-04-24 10:48:19,003 - MainThread - botocore.hooks - DEBUG - Event before-parameter-build.s3.ListBuckets: calling handler <function validate_bucket_name at 0x7f768ee29158>
2019-04-24 10:48:19,003 - MainThread - botocore.hooks - DEBUG - Event before-parameter-build.s3.ListBuckets: calling handler <bound method S3RegionRedirector.redirect_from_cache of <botocore.utils.S3RegionRedirector object at 0x7f768e376518>>
2019-04-24 10:48:19,003 - MainThread - botocore.hooks - DEBUG - Event before-call.s3.ListBuckets: calling handler <function add_expect_header at 0x7f768ee29620>
2019-04-24 10:48:19,004 - MainThread - botocore.hooks - DEBUG - Event before-call.s3.ListBuckets: calling handler <bound method S3RegionRedirector.set_request_url of <botocore.utils.S3RegionRedirector object at 0x7f768e376518>>
2019-04-24 10:48:19,004 - MainThread - botocore.endpoint - DEBUG - Making request for OperationModel(name=ListBuckets) (verify_ssl=True) with params: {'headers': {'User-Agent': 'aws-cli/1.11.13 Python/3.5.3 Linux/4.9.0-8-amd64 botocore/1.4.70'}, 'query_string': '', 'context': {'has_streaming_input': False, 'client_region': 'us-east-1', 'client_config': <botocore.config.Config object at 0x7f768e376240>, 'signing': {'bucket': None}}, 'url': 'http://127.0.0.1:8081/', 'method': 'GET', 'body': b'', 'url_path': '/'}
2019-04-24 10:48:19,004 - MainThread - botocore.hooks - DEBUG - Event request-created.s3.ListBuckets: calling handler <bound method RequestSigner.handler of <botocore.signers.RequestSigner object at 0x7f768e376080>>
2019-04-24 10:48:19,004 - MainThread - botocore.auth - DEBUG - Calculating signature using hmacv1 auth.
2019-04-24 10:48:19,004 - MainThread - botocore.auth - DEBUG - HTTP request method: GET
2019-04-24 10:48:19,005 - MainThread - botocore.auth - DEBUG - StringToSign:
GET


Wed, 24 Apr 2019 14:48:19 GMT
/
2019-04-24 10:48:19,016 - MainThread - botocore.endpoint - DEBUG - Sending http request: <PreparedRequest [GET]>
info: GET / 403 0ms -
2019-04-24 10:48:19,021 - MainThread - botocore.parsers - DEBUG - Response headers: {'Content-Type': 'application/xml', 'Date': 'Wed, 24 Apr 2019 14:48:19 GMT', 'Connection': 'keep-alive', 'Content-Length': '159'}
2019-04-24 10:48:19,021 - MainThread - botocore.parsers - DEBUG - Response body:
b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>AccessDenied</Code><Message>AWS authentication requires a valid Date or x-amz-date header</Message></Error>'
2019-04-24 10:48:19,022 - MainThread - botocore.hooks - DEBUG - Event needs-retry.s3.ListBuckets: calling handler <botocore.retryhandler.RetryHandler object at 0x7f768e368048>
2019-04-24 10:48:19,022 - MainThread - botocore.retryhandler - DEBUG - No retry needed.
2019-04-24 10:48:19,022 - MainThread - botocore.hooks - DEBUG - Event needs-retry.s3.ListBuckets: calling handler <bound method S3RegionRedirector.redirect_from_error of <botocore.utils.S3RegionRedirector object at 0x7f768e376518>>
2019-04-24 10:48:19,022 - MainThread - botocore.hooks - DEBUG - Event after-call.s3.ListBuckets: calling handler <function enhance_error_msg at 0x7f768fbc7bf8>
2019-04-24 10:48:19,023 - MainThread - awscli.clidriver - DEBUG - Exception caught in main()
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/awscli/clidriver.py", line 186, in main
    return command_table[parsed_args.command](remaining, parsed_args)
  File "/usr/lib/python3/dist-packages/awscli/customizations/commands.py", line 190, in __call__
    parsed_globals)
  File "/usr/lib/python3/dist-packages/awscli/customizations/commands.py", line 187, in __call__
    return self._run_main(parsed_args, parsed_globals)
  File "/usr/lib/python3/dist-packages/awscli/customizations/s3/subcommands.py", line 465, in _run_main
    self._list_all_buckets()
  File "/usr/lib/python3/dist-packages/awscli/customizations/s3/subcommands.py", line 530, in _list_all_buckets
    response_data = self.client.list_buckets()
  File "/usr/lib/python3/dist-packages/botocore/client.py", line 251, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/lib/python3/dist-packages/botocore/client.py", line 537, in _make_api_call
    raise ClientError(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the ListBuckets operation: AWS authentication requires a valid Date or x-amz-date header
2019-04-24 10:48:19,025 - MainThread - awscli.clidriver - DEBUG - Exiting with rc 255

An error occurred (AccessDenied) when calling the ListBuckets operation: AWS authentication requires a valid Date or x-amz-date header
```

</p>
</details>

I searched the codebase for that message and found exactly one place where it could be coming from: https://github.com/jamhall/s3rver/blob/be12af82f09a1028f2e4b2604a746561960d33ab/lib/middleware/authentication.js#L306

I got out Wireshark and watched the request flow through, and I can see that the request does actually contain a Date header:

![image](https://user-images.githubusercontent.com/7883777/56669948-f0e61100-667f-11e9-8093-4fc95a4cb135.png)

And then, just to paint a complete picture, here is the response viewed from Wireshark as well:

![image](https://user-images.githubusercontent.com/7883777/56670314-9ef1bb00-6680-11e9-8058-703ca42385a5.png)

Then I went into `s3rver/lib/middleware/authentication.js`, in `parseHeader()`, and added ``console.log(`headers is ${JSON.stringify(headers, null, '\t')}`);`` just before `const timestamp = headers["x-amz-date"] || headers["Date"];`.  And this is what I saw:

```
headers is {
	"host": "127.0.0.1:8081",
	"accept-encoding": "identity",
	"user-agent": "aws-cli/1.11.13 Python/3.5.3 Linux/4.9.0-8-amd64 botocore/1.4.70",
	"date": "Wed, 24 Apr 2019 15:22:17 GMT",
	"authorization": "AWS S3RVER:zfh9a506PMXgC2ds/rDmv0NDJ3g="
}
```

Apparently all of the header names get lowercased somewhere in the pipeline?

Then I changed that `timestamp` assignment to say `headers["date"]` instead of `headers["Date"]`, and then my `aws s3 ls` command worked!!

I'll create a PR for this simple fix.  Let me know if you think it's the right approach.

**Comment by kherock** [comment]
Sorry for the delay in publishing this - v3.1.0 has been released with this fix.

**Comment by Moonligth1995** [comment]
STATUS:200
x-luminati-ip:194.124.239.219
x-luminati-timeline:z382-init:0,auth:18,dns_resolve:11,ipc_find:25,ext_conn:23,zlum_ztun_conn:0,ztun_conn:87
content-type:image/png
content-length:130074
connection:keep-alive
x-amz-id-2:E43EX+0mYO4XLtNoiak/WyhT2lbDzdhBTcwG0TsZyea63chwmSNPP6GeSlh8C2KqzfEC/lGKSoQ=
x-amz-request-id:A257F70QSKAQ228M
date:Wed, 14 Jun 2023 21:49:41 GMT
last-modified:Thu, 01 Jun 2023 20:25:08 GMT
etag:"58af5f3e075fe35611cd424930655015"
x-amz-server-side-encryption:AES256
cache-control:max-age=31536000
accept-ranges:bytes
server:AmazonS3
x-cache:Hit from cloudfront
via:1.1 c74474051b84c739f39b09ca3fe33dac.cloudfront.net (CloudFront)
x-amz-cf-pop:LHR50-P7
x-amz-cf-id:Dsy5Jy1c1sU6We5og4RBO-6aUom6EiT6wIoaq6QCtwifBJY_d3KDWg==
age:26915
vary:Origin
x-lpm-port:24010
