### ISSUE TITLE
Use a mounted SMB drive with s3rver as directory

### ISSUE THREAD

**Issue by cr-solutions** [jamhall/s3rver#75]
Hello,

we like to use a mounted SMB drive via S3, but we get the following error.

Our SMB drive mount:

`\\192.168.2.17/smb-www on /var/www type cifs (rw,nosuid,nodev,noexec,relatime,vers=1.0,cache=strict,username=administrator,domain=xxx,uid=0,forceuid,gid=33,forcegid,addr=192.168.2.17,file_mode=0775,dir_mode=0775,iocharset=iso8859-1,nounix,nobrl,noperm,rsize=61440,wsize=16580,actimeo=1,_netdev,user)
`

Start of s3rver:

`s3rver -h 192.168.2.16 -p 8000 -d /var/www/`

Error after access:
```
now listening on host 192.168.2.16 and port 8000
info: [S3rver] GET / 500 1192 - 9.980 ms
Error: ENOENT: no such file or directory, stat '/var/www/SMB-PUBLIC (192.168.2.17) (P) - Verknï¿½pfung.lnk'
    at Object.fs.statSync (fs.js:955:11)
    at Object.statSync (/usr/lib/node_modules/s3rver/node_modules/graceful-fs/polyfills.js:297:22)
    at /usr/lib/node_modules/s3rver/lib/file-store.js:40:21
    at Array.filter (<anonymous>)
    at Object.getBuckets (/usr/lib/node_modules/s3rver/lib/file-store.js:39:35)
    at getBuckets (/usr/lib/node_modules/s3rver/lib/controllers.js:154:31)
    at Layer.handle [as handle_request] (/usr/lib/node_modules/s3rver/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/lib/node_modules/s3rver/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/usr/lib/node_modules/s3rver/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/usr/lib/node_modules/s3rver/node_modules/express/lib/router/layer.js:95:5)

```

**Comment by leontastic** [comment]
Closing due to staleness
