### ISSUE TITLE
Error  ERR_OSSL_EVP_UNSUPPORTED error:0308010C:digital envelope routines::unsupported

### ISSUE THREAD

**Issue by sytolk** [jamhall/s3rver#818]
I'm using aws-sdk v3 in S3 client node.js app. Before to move (copy and delete) `sample_exif[iptc].jpg` object in `empty_folder/` dir I dont have this issue after listing objects in `empty_folder/` directory.

```
info: Copied object "sample_exif[iptc].jpg" from bucket "supported-filestypes" into bucket "supported-filestypes" with key of "empty_folder/sample_exif[iptc].jpg"
info: PUT /supported-filestypes/empty_folder/sample_exif%5Biptc%5D.jpg?x-id=CopyObject 200 4ms 186b
info: OPTIONS /supported-filestypes/sample_exif%5Biptc%5D.jpg?x-id=DeleteObject 200 1ms 0b
info: DELETE /supported-filestypes/sample_exif%5Biptc%5D.jpg?x-id=DeleteObject 204 2ms 
info: OPTIONS /supported-filestypes/empty_folder/.ts/sample_exif%5Biptc%5D.jpg.json?x-id=CopyObject 200 1ms 0b
info: OPTIONS /supported-filestypes/empty_folder/.ts/sample_exif%5Biptc%5D.jpg.jpg?x-id=CopyObject 200 2ms 0b
info: OPTIONS /supported-filestypes/.ts/sample_exif%5Biptc%5D.jpg.json?response-cache-control=no-cache&x-id=GetObject 200 2ms 0b
error: Object ".ts/sample_exif[iptc].jpg.json" in bucket "supported-filestypes" does not exist
error: Error copying object ".ts/sample_exif[iptc].jpg.json" from bucket "supported-filestypes" into bucket "supported-filestypes" with key of "empty_folder/.ts/sample_exif[iptc].jpg.json"
info: PUT /supported-filestypes/empty_folder/.ts/sample_exif%5Biptc%5D.jpg.json?x-id=CopyObject 404 1ms -
info: GET /supported-filestypes/.ts/sample_exif%5Biptc%5D.jpg.json?response-cache-control=no-cache&x-id=GetObject 404 1ms -
info: Copied object ".ts/sample_exif[iptc].jpg.jpg" from bucket "supported-filestypes" into bucket "supported-filestypes" with key of "empty_folder/.ts/sample_exif[iptc].jpg.jpg"
info: PUT /supported-filestypes/empty_folder/.ts/sample_exif%5Biptc%5D.jpg.jpg?x-id=CopyObject 200 5ms 186b
info: OPTIONS /supported-filestypes/.ts/sample_exif%5Biptc%5D.jpg.jpg?x-id=DeleteObject 200 1ms 0b
info: DELETE /supported-filestypes/.ts/sample_exif%5Biptc%5D.jpg.jpg?x-id=DeleteObject 204 2ms 
info: HEAD /supported-filestypes/empty_folder/sample_exif%5Biptc%5D.jpg 200 1ms 99.76kb
info: OPTIONS /supported-filestypes/empty_folder/.ts/sample_exif%5Biptc%5D.jpg.jpg 200 1ms 0b
info: HEAD /supported-filestypes/empty_folder/.ts/sample_exif%5Biptc%5D.jpg.jpg 200 1ms 48.7kb
info: OPTIONS /supported-filestypes/empty_folder/.ts/sample_exif%5Biptc%5D.jpg.json?response-cache-control=no-cache&x-id=GetObject 200 1ms 0b
info: GET /supported-filestypes/empty_folder/.ts/sample_exif%5Biptc%5D.jpg.json?response-cache-control=no-cache&x-id=GetObject 404 0ms -
info: OPTIONS /supported-filestypes/empty_folder/ 200 2ms 0b
info: HEAD /supported-filestypes/empty_folder/ 404 1ms -
info: OPTIONS /supported-filestypes/?delimiter=%2F&list-type=2&max-keys=1&prefix=empty_folder%2F 200 2ms 0b
info: Fetched bucket "supported-filestypes" with options {"delimiter":"/","maxKeys":1,"prefix":"empty_folder/","fetchOwner":false}
info: Found 1 objects for bucket "supported-filestypes"
error: Error listing objects in bucket "supported-filestypes" {"code":"ERR_OSSL_EVP_UNSUPPORTED","library":"digital envelope routines","reason":"unsupported"}
info: GET /supported-filestypes/?delimiter=%2F&list-type=2&max-keys=1&prefix=empty_folder%2F 500 4ms -

  Error: error:0308010C:digital envelope routines::unsupported
      at Cipheriv.createCipherBase (node:internal/crypto/cipher:122:19)
      at Cipheriv.createCipherWithIV (node:internal/crypto/cipher:141:3)
      at new Cipheriv (node:internal/crypto/cipher:249:3)
      at Object.createCipheriv (node:crypto:141:10)
      at generateContinuationToken (/Users/sytolk/IdeaProjects/tagspaces3/node_modules/s3rver/lib/controllers/bucket.js:20:25)
      at Object.getBucket (/Users/sytolk/IdeaProjects/tagspaces3/node_modules/s3rver/lib/controllers/bucket.js:248:19)
      at async bucketExists (/Users/sytolk/IdeaProjects/tagspaces3/node_modules/s3rver/lib/controllers/bucket.js:51:13)
      at async queryMethod (/Users/sytolk/IdeaProjects/tagspaces3/node_modules/s3rver/lib/routes.js:36:5)
      at async responseHeaderOverride (/Users/sytolk/IdeaProjects/tagspaces3/node_modules/s3rver/lib/middleware/response-header-override.js:61:9)
      at async /Users/sytolk/IdeaProjects/tagspaces3/node_modules/s3rver/lib/s3rver.js:53:9

info: Fetched bucket "supported-filestypes" with options {"delimiter":"/","maxKeys":1,"prefix":"empty_folder/","fetchOwner":false}
info: Found 1 objects for bucket "supported-filestypes"
error: Error listing objects in bucket "supported-filestypes" {"code":"ERR_OSSL_EVP_UNSUPPORTED","library":"digital envelope routines","reason":"unsupported"}
info: GET /supported-filestypes/?delimiter=%2F&list-type=2&max-keys=1&prefix=empty_folder%2F 500 2ms -

  Error: error:0308010C:digital envelope routines::unsupported
      at Cipheriv.createCipherBase (node:internal/crypto/cipher:122:19)
      at Cipheriv.createCipherWithIV (node:internal/crypto/cipher:141:3)
      at new Cipheriv (node:internal/crypto/cipher:249:3)
      at Object.createCipheriv (node:crypto:141:10)
      at generateContinuationToken (/Users/sytolk/IdeaProjects/tagspaces3/node_modules/s3rver/lib/controllers/bucket.js:20:25)
      at Object.getBucket (/Users/sytolk/IdeaProjects/tagspaces3/node_modules/s3rver/lib/controllers/bucket.js:248:19)
      at async bucketExists (/Users/sytolk/IdeaProjects/tagspaces3/node_modules/s3rver/lib/controllers/bucket.js:51:13)
      at async queryMethod (/Users/sytolk/IdeaProjects/tagspaces3/node_modules/s3rver/lib/routes.js:36:5)
      at async responseHeaderOverride (/Users/sytolk/IdeaProjects/tagspaces3/node_modules/s3rver/lib/middleware/response-header-override.js:61:9)
      at async /Users/sytolk/IdeaProjects/tagspaces3/node_modules/s3rver/lib/s3rver.js:53:9

info: Fetched bucket "supported-filestypes" with options {"delimiter":"/","maxKeys":1,"prefix":"empty_folder/","fetchOwner":false}
info: Found 1 objects for bucket "supported-filestypes"
error: Error listing objects in bucket "supported-filestypes" {"code":"ERR_OSSL_EVP_UNSUPPORTED","library":"digital envelope routines","reason":"unsupported"}
info: GET /supported-filestypes/?delimiter=%2F&list-type=2&max-keys=1&prefix=empty_folder%2F 500 3ms -

  Error: error:0308010C:digital envelope routines::unsupported
      at Cipheriv.createCipherBase (node:internal/crypto/cipher:122:19)
      at Cipheriv.createCipherWithIV (node:internal/crypto/cipher:141:3)
      at new Cipheriv (node:internal/crypto/cipher:249:3)
      at Object.createCipheriv (node:crypto:141:10)
      at generateContinuationToken (/Users/sytolk/IdeaProjects/tagspaces3/node_modules/s3rver/lib/controllers/bucket.js:20:25)
      at Object.getBucket (/Users/sytolk/IdeaProjects/tagspaces3/node_modules/s3rver/lib/controllers/bucket.js:248:19)
      at async bucketExists (/Users/sytolk/IdeaProjects/tagspaces3/node_modules/s3rver/lib/controllers/bucket.js:51:13)
      at async queryMethod (/Users/sytolk/IdeaProjects/tagspaces3/node_modules/s3rver/lib/routes.js:36:5)
      at async responseHeaderOverride (/Users/sytolk/IdeaProjects/tagspaces3/node_modules/s3rver/lib/middleware/response-header-override.js:61:9)
      at async /Users/sytolk/IdeaProjects/tagspaces3/node_modules/s3rver/lib/s3rver.js:53:9

```

The same error log after copy objects in empty_folder/ and list dir next

```
info: Copied object ".ts/sample_exif[iptc].jpg.jpg" from bucket "supported-filestypes" into bucket "supported-filestypes" with key of "empty_folder/.ts/sample_exif[iptc].jpg.jpg"
info: PUT /supported-filestypes/empty_folder/.ts/sample_exif%5Biptc%5D.jpg.jpg?x-id=CopyObject 200 6ms 186b
info: OPTIONS /supported-filestypes/empty_folder/.ts/sample_exif%5Biptc%5D.jpg.json 200 1ms 0b
info: HEAD /supported-filestypes/empty_folder/.ts/sample_exif%5Biptc%5D.jpg.jpg 200 2ms 48.7kb
info: HEAD /supported-filestypes/empty_folder/.ts/sample_exif%5Biptc%5D.jpg.json 404 1ms -
info: OPTIONS /supported-filestypes/?delimiter=%2F&list-type=2&max-keys=1&prefix=empty_folder%2F.ts%2Fsample_exif%5Biptc%5D.jpg.json 200 1ms 0b
info: OPTIONS /supported-filestypes/empty_folder/.ts/sample_exif%5Biptc%5D.jpg.jpg.json?response-cache-control=no-cache&x-id=GetObject 200 1ms 0b
info: Fetched bucket "supported-filestypes" with options {"delimiter":"/","maxKeys":1,"prefix":"empty_folder/.ts/sample_exif[iptc].jpg.json","fetchOwner":false}
info: Found 0 objects for bucket "supported-filestypes"
info: GET /supported-filestypes/?delimiter=%2F&list-type=2&max-keys=1&prefix=empty_folder%2F.ts%2Fsample_exif%5Biptc%5D.jpg.json 200 5ms 315b
info: GET /supported-filestypes/empty_folder/.ts/sample_exif%5Biptc%5D.jpg.jpg.json?response-cache-control=no-cache&x-id=GetObject 404 5ms -
info: OPTIONS /supported-filestypes/empty_folder/ 200 2ms 0b
info: HEAD /supported-filestypes/empty_folder/ 404 2ms -
info: OPTIONS /supported-filestypes/?delimiter=%2F&list-type=2&max-keys=1&prefix=empty_folder%2F 200 0ms 0b
info: Fetched bucket "supported-filestypes" with options {"delimiter":"/","maxKeys":1,"prefix":"empty_folder/","fetchOwner":false}
info: Found 1 objects for bucket "supported-filestypes"
error: Error listing objects in bucket "supported-filestypes" {"code":"ERR_OSSL_EVP_UNSUPPORTED","library":"digital envelope routines","reason":"unsupported"}
info: GET /supported-filestypes/?delimiter=%2F&list-type=2&max-keys=1&prefix=empty_folder%2F 500 2ms -

  Error: error:0308010C:digital envelope routines::unsupported
      at Cipheriv.createCipherBase (node:internal/crypto/cipher:122:19)
      at Cipheriv.createCipherWithIV (node:internal/crypto/cipher:141:3)
      at new Cipheriv (node:internal/crypto/cipher:249:3)
      at Object.createCipheriv (node:crypto:141:10)
      at generateContinuationToken (/Users/sytolk/IdeaProjects/tagspaces3/node_modules/s3rver/lib/controllers/bucket.js:20:25)
      at Object.getBucket (/Users/sytolk/IdeaProjects/tagspaces3/node_modules/s3rver/lib/controllers/bucket.js:248:19)
      at async bucketExists (/Users/sytolk/IdeaProjects/tagspaces3/node_modules/s3rver/lib/controllers/bucket.js:51:13)
      at async queryMethod (/Users/sytolk/IdeaProjects/tagspaces3/node_modules/s3rver/lib/routes.js:36:5)
      at async responseHeaderOverride (/Users/sytolk/IdeaProjects/tagspaces3/node_modules/s3rver/lib/middleware/response-header-override.js:61:9)
      at async /Users/sytolk/IdeaProjects/tagspaces3/node_modules/s3rver/lib/s3rver.js:53:9

```

**Comment by sytolk** [comment]
fixed adding env like `cross-env NODE_OPTIONS=--openssl-legacy-provider` before to start s3rver
